server:
  port: 8080

spring:
  application:
    name: customer
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/customer
    username: amigoscode
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
        ddl-auto: create-drop
        show-sql: true
service:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch_registry: true
      register-with-eureka: true